### ISSUE TITLE
Support line comments

### ISSUE THREAD

**Issue by paulcsmith** [BlakeWilliams/envy#1]
Hey Blake,

In my .env file I have something like this:

```
# Sandbox Key
KEY=foo
# Production Key
KEY=real_key
```

It fails to parse this since the line has no key/value pair. I think it would be great if it did nothing if a line started with a `#`

**Comment by BlakeWilliams** [comment]
Added a fix in #2.

**Comment by BlakeWilliams** [comment]
Released to hex as `0.0.2`.
