### ISSUE TITLE
Use System.get_env("MIX_ENV") == "prod" instead of Mix?

### ISSUE THREAD

**Issue by lorenzosinisi** [BlakeWilliams/envy#13]
Very nice app, I would like to use it in one of my projects but I noticed that uses Mix to check the current `env` https://github.com/BlakeWilliams/envy/blob/9caa41ee87ae8bf0ca45f2eb08fe9792d88a02ec/lib/envy.ex#L30> 

What about using `System.get_env("MIX_ENV") == "prod"` so that `mix` becomes unnecessary?

I could open a PR to change this, let me know! 👍

**Comment by BlakeWilliams** [comment]
Hey @lorenzosinisi, I think Mix provides some nice to haves here like setting a default env and etc.

What's your use case for not using env so I can understand the change more?

**Comment by lorenzosinisi** [comment]
I was simply trying to comply to the official documentation that states: 

`
Mix is a build tool and, as such, it is not always expected to be available in production, especially if your team uses explicit build steps. Therefore, it is recommended to access Mix.env only in configuration files and inside mix.exs, never in your application code (lib).
`
Via https://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html 

So in order to give other devs the least amount of surprise, I would avoid using Mix in production when having another non-trivial alternative :) That's it 

What do you think?

**Comment by BlakeWilliams** [comment]
Ah gotcha, Envy is really a tool for development and not meant for use in production so I think we're safe there. At least by intent.

**Comment by lorenzosinisi** [comment]
Oh yeah, I understand your point @BlakeWilliams. I was probably confused by seeing the example where Envy is added in the `start/2` function. But thanks for the clarification :) Nice library!

**Comment by BlakeWilliams** [comment]
No problem! It was a worthwhile discussion.

Thanks!
